Deep Learning VIA ANN

Importing Libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.20.0'

Importing Dataset

In [3]:
dataset = pd.read_csv('American Express Data Analysis.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)

[[553.0 'Delhi' 'Female' ... 4.0 1.0 274150.0]
 [447.0 'Bengaluru' 'Male' ... 4.0 1.0 519360.0]
 [501.0 'Delhi' 'Female' ... 4.0 1.0 545501.0]
 ...
 [553.0 'Delhi' 'Male' ... 4.0 1.0 180031.0]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]]


Encoding Categorical Data

Gender Column: Label Encoding

In [5]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
X[:, 2] = label_encoder.fit_transform(X[:, 2])

In [6]:
print(X)

[[553.0 'Delhi' 0 ... 4.0 1.0 274150.0]
 [447.0 'Bengaluru' 1 ... 4.0 1.0 519360.0]
 [501.0 'Delhi' 0 ... 4.0 1.0 545501.0]
 ...
 [553.0 'Delhi' 1 ... 4.0 1.0 180031.0]
 [nan nan 2 ... nan nan nan]
 [nan nan 2 ... nan nan nan]]


 Geography Column: One-Hot Encoding

In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))


In [8]:
print(X)

[[0.0 1.0 0.0 ... 4.0 1.0 274150.0]
 [1.0 0.0 0.0 ... 4.0 1.0 519360.0]
 [0.0 1.0 0.0 ... 4.0 1.0 545501.0]
 ...
 [0.0 1.0 0.0 ... 4.0 1.0 180031.0]
 [0.0 0.0 0.0 ... nan nan nan]
 [0.0 0.0 0.0 ... nan nan nan]]


Splitting Dataset into Training and Testing Sets

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

Feature Scaling

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

ANN

Defining Model for ANN

In [11]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [12]:
input_dim = X_train.shape[1]

Adding first and second hidden layer and output layer

In [13]:
model = Sequential([Dense(64,activation='relu',input_shape= (input_dim,)),
                  Dense(32,activation='relu'),                            
                  Dense(1,activation='sigmoid')])

C:\Users\harsh\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


ANN Training

Compiling

In [14]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 64)                  │             832 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 32)                  │           2,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 1)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

Training

In [ ]:
history=model.fit(X_train,Y_train,batch_size=32, epochs=55,validation_split=0.2)

Epoch 1/55
199/199 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7762 - loss: nan - val_accuracy: 0.8068 - val_loss: nan
Epoch 2/55
199/199 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7904 - loss: nan - val_accuracy: 0.8068 - val_loss: nan
Epoch 3/55
199/199 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7904 - loss: nan - val_accuracy: 0.8068 - val_loss: nan
Epoch 4/55
199/199 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7904 - loss: nan - val_accuracy: 0.8068 - val_loss: nan
Epoch 5/55
199/199 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7904 - loss: nan - val_accuracy: 0.8068 - val_loss: nan
Epoch 6/55
199/199 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7904 - loss: nan - val_accuracy: 0.8068 - val_loss: nan
Epoch 7/55
199/199 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7904 - loss: nan - val_accuracy: 0.8068 - val_loss: nan
Epoch 8/55
199/199 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7904 - loss: nan - val_accuracy: 0.8068 - val_loss: nan
Epoch 9/55
199/199 ━━━━━

Evaluating

In [ ]:
loss,accuracy=model.evaluate(X_test,Y_test)
print(f"Test Loss: {loss:.4f}")
print(f"Accuracy: {accuracy:.4f}")

Predictions

Single Prediction

In [ ]:
print(model.predict(sc.transform([[1.0, 0.0, 0.0, 447, 1, 31, 7, 0.0, 4, 1, 519360]]))>0.5)predictions=model.predict(X_test)
Y_pred=model.predict(X_test)
Y_pred=(y_pred>0.5)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1),Y_test.reshape(len(Y_test),1)),1))

Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(Y_test,Y_pred)
print(cm)
accuracy_score(Y_test,Y_pred)